# -*- coding: utf-8 -*-
"""Encounter catalog — 50+ real historical decision points."""
from __future__ import annotations

from extensions.history_events.encounters import HistoricalEncounter


def _e(
    id: str,
    title: str,
    era_bucket: str,
    era: str,
    region: str,
    category: str,
    setup: str,
    question: str,
    historical_context: str,
    what_happened: str,
    key_factors: tuple[str, ...],
    image_hint: str = "",
) -> HistoricalEncounter:
    return HistoricalEncounter(
        id=id,
        title=title,
        era_bucket=era_bucket,
        era=era,
        region=region,
        category=category,
        setup=setup,
        question=question,
        historical_context=historical_context,
        what_happened=what_happened,
        key_factors=key_factors,
        image_hint=image_hint or title,
    )


ALL_ENCOUNTERS: list[HistoricalEncounter] = [
    _e(
        "thermopylae_480",
        "Thermopylae — Hold the Pass",
        "ancient",
        "480 BCE",
        "Greece",
        "Ancient warfare",
        "Persian King Xerxes has crossed into Greece with a vast army. A narrow coastal pass at Thermopylae is the choke point. Spartan King Leonidas leads roughly seven thousand Greeks. Scouts report the Immortals may outflank the pass via a mountain path.",
        "Facing overwhelming numbers and a possible flanking route, what strategy do you advocate for the allied force at Thermopylae?",
        "Leonidas held the pass for days. Ephialtes betrayed the Anopaia path. Leonidas dismissed most allies and fought a rear-guard.",
        "Leonidas sent most allies away and stayed with roughly three hundred Spartans. They were annihilated but bought time for Greek naval unity.",
        ("terrain advantage", "flank threat", "buying time for fleet", "sacrificial rear-guard", "morale and symbolism"),
        "Spartan warriors at mountain pass battle",
    ),
    _e(
        "cannae_216",
        "Cannae — Roman Deployment",
        "ancient",
        "216 BCE",
        "Italy",
        "Ancient warfare",
        "Hannibal has destroyed a Roman army at Lake Trasimene. Consul Varro and Paullus command the largest Roman force yet — roughly eighty thousand against Hannibal's veterans on open ground near Cannae.",
        "As a Roman adviser on the eve of battle, how do you recommend deploying legions and cavalry against Hannibal's center-heavy line?",
        "Romans massed infantry deep in the center to break Hannibal's middle. Hannibal's double envelopment surrounded and annihilated them.",
        "Rome suffered perhaps fifty thousand casualties in one day — its worst defeat. Fabian delay tactics gained favor afterward.",
        ("avoid overcommitting center", "protect flanks", "cavalry parity", "Fabian alternative", "command unity"),
        "ancient Roman legions battle Hannibal",
    ),
    _e(
        "caesar_ides_44",
        "Rome — Ides of March Warning",
        "ancient",
        "44 BCE",
        "Rome",
        "Politics & assassination",
        "Caesar has been named dictator perpetuo. The Senate resents his power; rumors of kingship circulate. A soothsayer and spouse Calpurnia warn him of danger on the Ides of March. Brutus and Cassius move among senators.",
        "As a loyal but worried adviser, what do you urge Caesar to do on March 15 regarding the Senate meeting?",
        "Multiple warnings reached Caesar. He dismissed fears and entered the Senate where conspirators stabbed him.",
        "Caesar was assassinated on the Senate floor. Civil war followed; the Republic effectively ended.",
        ("security vs appearance of fear", "loyalty of allies", "postponing Senate", "bodyguards", "political backlash"),
        "Julius Caesar Roman Senate assassination",
    ),
    _e(
        "masada_73",
        "Masada — Siege Endgame",
        "ancient",
        "73 CE",
        "Judea",
        "Siege warfare",
        "Roman Legio X surrounds the fortress of Masada held by Sicarii rebels. A massive ramp nears completion. Water is scarce inside; hope of relief is gone. Eleazar ben Ya'ir addresses defenders.",
        "With the ramp almost complete, what course do you argue the defenders should take?",
        "According to Josephus, defenders chose mass suicide rather than capture after a speech by Eleazar.",
        "Romans breached the fortress to find the dead. Masada became a symbol of resistance.",
        ("honor vs surrender", "civilian non-combatants", "negotiated terms", "night sortie", "symbolic legacy"),
        "ancient desert fortress siege Masada",
    ),
    _e(
        "hastings_1066",
        "Hastings — Harold's Position",
        "medieval",
        "1066",
        "England",
        "Medieval warfare",
        "Harold Godwinson has force-marched south after defeating Hardrada at Stamford Bridge. William's Normans advance near Senlac Hill. Harold's fyrd is tired; brothers urge holding the high ground versus charging.",
        "Before battle begins, what deployment and discipline orders do you give the English shield wall?",
        "Harold held the ridge. Norman feigned retreats lured breaks in the line. Harold was killed; Normans won.",
        "Norman conquest of England followed. Anglo-Saxon elite was replaced.",
        ("hold high ground", "avoid breaking ranks", "cavalry threat", "exhausted troops", "reserve management"),
        "Battle of Hastings 1066 Norman knights",
    ),
    _e(
        "magna_carta_1215",
        "Runnymede — Barons vs King John",
        "medieval",
        "1215",
        "England",
        "Law & politics",
        "Rebel barons have captured London. King John faces civil war. They demand written limits on royal power, relief from arbitrary fines, and lawful judgment. John needs time and foreign allies.",
        "As a baronial negotiator, which demands are non-negotiable versus what you might trade for enforcement mechanisms?",
        "Barons forced John to seal Magna Carta at Runnymede. Pope annulled it; war resumed briefly.",
        "Magna Carta was reissued after John's death and became a foundational rights document.",
        ("written limits on king", "enforcement council", "feudal relief", "foreign intervention risk", "practical enforceability"),
        "King John barons Magna Carta medieval",
    ),
    _e(
        "black_death_1348",
        "Florence — Plague Orders",
        "medieval",
        "1348",
        "Italy",
        "Public health",
        "The pestilence has reached Florence. Boccaccio later describes flight and paralysis. Trade and church rituals continue. Some urge quarantine; merchants fear economic collapse.",
        "As a city official, what public-health and social orders do you issue in the first month of the outbreak?",
        "Italian cities experimented with quarantine boards and cordons later; contemporary responses were chaotic.",
        "Perhaps half of Florence's population died. Labor scarcity reshaped feudal relations.",
        ("quarantine feasibility", "trade vs safety", "religious processions", "burial practices", "food supply"),
        "medieval plague city Florence",
    ),
    _e(
        "agincourt_1415",
        "Agincourt — Mud and Archers",
        "medieval",
        "1415",
        "France",
        "Medieval warfare",
        "Henry V's exhausted English army is blocked by a much larger French force near Agincourt. Heavy rain turned the field to mud. French knights are eager to charge. English longbowmen have stakes.",
        "How do you recommend Henry deploy archers and men-at-arms before the French advance?",
        "English archers devastated French knights stuck in mud. Henry ordered killing of prisoners amid a feared counterattack.",
        "Stunning English victory; French nobility suffered catastrophic losses.",
        ("terrain and mud", "longbow volleys", "stakes protection", "prisoner dilemma", "French impatience"),
        "Battle of Agincourt longbowmen mud",
    ),
    _e(
        "viking_paris_885",
        "Siege of Paris — Viking Demand",
        "medieval",
        "885–886",
        "Frankish Empire",
        "Medieval siege",
        "A large Viking fleet has sailed up the Seine. Count Odo defends bridges on the Île de la Cité. Charles the Fat is slow to relieve the city. Citizens face famine. Vikings offer to leave for payment.",
        "As adviser to the defenders, do you hold for relief, negotiate tribute, or sortie — on what terms?",
        "Odo held through winter. Charles paid Danegeld and let Vikings plunder Burgundy instead.",
        "Paris survived; Odo's reputation soared and he later became king.",
        ("bridge defense", "food reserves", "imperial reliability", "tribute vs honor", "civilian survival"),
        "Viking siege medieval Paris",
    ),
    _e(
        "constantinople_1453",
        "Fall of Constantinople — Final Walls",
        "medieval",
        "1453",
        "Byzantine Empire",
        "Siege warfare",
        "Mehmed II's cannons breach sections of the Theodosian Walls nightly repaired by Byzantines. A chain blocks the Golden Horn. Constantine XI commands roughly seven thousand defenders. Allies are divided.",
        "With a major assault imminent, what defensive and diplomatic moves do you urge before the next wave?",
        "Mehmed moved ships overland into the Golden Horn. City fell May 29; Constantine died fighting.",
        "Constantinople became Istanbul; Byzantine Empire ended.",
        ("night repairs", "Golden Horn naval threat", "ally coordination", "garrison morale", "limited relief"),
        "Constantinople siege Ottoman cannons",
    ),
    _e(
        "columbus_1492",
        "Atlantic Crossing — Mutiny Risk",
        "early_modern",
        "1492",
        "Atlantic",
        "Exploration",
        "Columbus's three ships have been at sea weeks longer than crews expected. Compasses behave oddly. Men demand turning back. Land is uncertain. Columbus privately logs lower distances than sailors see.",
        "As ship captain facing open mutiny talk, what orders and concessions do you make to keep the voyage westward?",
        "Columbus negotiated a deadline to turn back if no land; land was sighted before it.",
        "The voyage reached the Caribbean, opening sustained contact between Europe and the Americas.",
        ("crew morale", "navigation uncertainty", "deadline credibility", "supply state", "leadership authority"),
        "Columbus ships Atlantic exploration 1492",
    ),
    _e(
        "magellan_strait_1520",
        "Magellan — Unknown Strait",
        "early_modern",
        "1520",
        "South America",
        "Exploration",
        "Magellan's fleet is exhausted and mutinous. A narrow fog-choked strait may be a dead end. Winter approaches. Captains urge turning back.",
        "What course do you recommend for the fleet — and how do you manage crew dissent?",
        "Magellan entered the strait, took thirty-eight days, lost a ship to desertion, crossed the Pacific.",
        "Only one ship and eighteen men returned in 1522 — first circumnavigation.",
        ("risk of trap vs reward", "crew morale", "seasonal weather", "scouting parties", "supply state"),
        "Magellan strait ships fog Patagonia",
    ),
    _e(
        "armada_1588",
        "Spanish Armada — English Response",
        "early_modern",
        "1588",
        "English Channel",
        "Naval warfare",
        "Philip II's Armada approaches to escort an army against England. English squadrons are faster but outgunned in close fight. Options include fire ships, blockade in Channel, or letting Spanish anchor.",
        "As Elizabeth's naval adviser, what strategy do you recommend for the coming nights in the Channel?",
        "English harried Armada; fire ships at Calais broke formation. Storms destroyed much on return.",
        "Armada failed; English naval confidence rose.",
        ("fire ships timing", "avoid boarding fight", "weather factor", "Dunkirk anchorage", "supply lines"),
        "Spanish Armada English Channel 1588",
    ),
    _e(
        "salem_trials_1692",
        "Salem — Accusations Spread",
        "early_modern",
        "1692",
        "Massachusetts",
        "Law & society",
        "Girls suffer fits; women are accused of witchcraft. Confessions multiply. Spectral evidence is admitted. Jails fill; public fear demands action.",
        "As a magistrate, what rules of evidence do you insist on before new indictments?",
        "Courts accepted spectral evidence; executions continued until standards were challenged.",
        "Twenty executed before governor dissolved the court; later seen as mass hysteria.",
        ("reject spectral evidence", "due process", "separate investigation", "cooling panic", "evidentiary bar"),
        "Salem witch trials colonial courtroom",
    ),
    _e(
        "mutiny_bounty_1789",
        "HMS Bounty — Tahiti Departure",
        "early_modern",
        "1789",
        "Pacific",
        "Exploration & mutiny",
        "HMS Bounty spent five months in Tahiti. Discipline frayed; Bligh is harsh. Crew resent captain. Plants crowd the ship. Voyage to West Indies lies ahead.",
        "As senior officer, what steps restore discipline and prevent conflict before leaving Tahiti?",
        "Bligh's strict rule alienated officers; Christian led mutiny after departure.",
        "Bligh sailed 3,600 miles in an open boat to safety; mutineers settled Pitcairn.",
        ("crew grievances", "leadership style", "loyal vs disaffected", "Tahitian ties", "early intervention"),
        "HMS Bounty ship Tahiti mutiny",
    ),
    _e(
        "boston_tea_1773",
        "Boston — Tea Crisis",
        "early_modern",
        "1773",
        "Massachusetts",
        "Revolution",
        "Parliament's Tea Act lets the East India Company undercut smugglers. Sons of Liberty oppose any tax precedent. Ships sit in harbor with deadlines to unload. Governor refuses to let them sail away.",
        "As a colonial leader, what action do you support when the final deadline arrives — and how do you justify it?",
        "Protesters boarded ships and dumped tea; Parliament passed Coercive Acts.",
        "Escalation toward revolution accelerated after Boston Port Act.",
        ("tax precedent", "economic boycott", "property destruction ethics", "British retaliation", "public unity"),
        "Boston Tea Party harbor 1773",
    ),
    _e(
        "yorktown_1781",
        "Yorktown — Trap Cornwallis",
        "early_modern",
        "1781",
        "Virginia",
        "Revolutionary war",
        "Cornwallis has fortified Yorktown on a peninsula. French fleet must block the Chesapeake. Washington debates attacking now versus waiting. Clinton could relieve by sea.",
        "As allied commander, what timeline do you set for siege and naval coordination?",
        "French fleet won at Chesapeake; combined siege forced Cornwallis to surrender.",
        "Major British army captured; peace negotiations followed.",
        ("naval blockade", "siege lines", "relief window", "French coordination", "civilian impact"),
        "Siege of Yorktown American Revolution",
    ),
    _e(
        "haitian_revolution_1801",
        "Saint-Domingue — Toussaint's Constitution",
        "early_modern",
        "1801",
        "Caribbean",
        "Revolution & empire",
        "Former slave armies control Saint-Domingue. Toussaint invades Santo Domingo. Napoleon seeks to restore slavery. Toussaint names himself governor-for-life while claiming loyalty to France.",
        "As Toussaint's adviser, how do you balance autonomy, economic recovery, and avoiding a French expedition?",
        "Toussaint placated France while securing emancipation; Napoleon sent Leclerc anyway.",
        "French landed 1802; rebellion under Dessalines won independence in 1804.",
        ("diplomatic ambiguity", "plantation labor", "military readiness", "French intentions", "faction unity"),
        "Haitian revolution Caribbean colonial",
    ),
    _e(
        "louisiana_1803",
        "Louisiana Purchase — Constitutional Doubt",
        "early_modern",
        "1803",
        "USA",
        "Diplomacy & expansion",
        "Napoleon offers all of Louisiana unexpectedly. Jefferson doubts he can buy territory constitutionally. Federalists warn of too much land. Opportunity may vanish if delayed.",
        "As Jefferson's adviser, do you seize the offer, seek amendment, or negotiate narrower terms?",
        "Jefferson set aside strict construction doubts and pursued treaty ratification.",
        "U.S. doubled in size for $15 million; westward expansion accelerated.",
        ("constitutional authority", "timing with Napoleon", "Federalist opposition", "exploration cost", "Native nations"),
        "Louisiana Purchase 1803 American frontier",
    ),
    _e(
        "waterloo_1815",
        "Waterloo — Prussian Arrival",
        "nineteenth",
        "1815",
        "Belgium",
        "Napoleonic wars",
        "Napoleon attacks Wellington before Blücher's Prussians unite. Hougoumont and La Haye Sainte hold the center. Mud delays cannon. Blücher is wounded but claims he will come.",
        "As Wellington's staff officer, how do you allocate reserves while uncertain Prussian timing?",
        "Wellington held until Blücher arrived late afternoon; allied counterattack won.",
        "Napoleon's final defeat; Bourbon restoration followed.",
        ("hold ridge", "Prussian coordination", "farm strongpoints", "cavalry timing", "casualty trade-offs"),
        "Battle of Waterloo 1815",
    ),
    _e(
        "charge_light_brigade_1854",
        "Balaclava — Orders to the Light Brigade",
        "nineteenth",
        "1854",
        "Crimea",
        "Military blunder",
        "Raglan orders cavalry to 'prevent the enemy carrying away the guns.' From the valley floor Lucan sees only guns at the end of a mile-long valley lined with Russian batteries.",
        "As staff officer when the order arrives, what do you recommend before any charge?",
        "Miscommunication led to frontal charge into crossfire; wrong objective.",
        "Roughly 40% casualties; tactically futile but mythologized.",
        ("clarify objective", "visible vs intended guns", "suicidal terrain", "refuse absurd orders", "chain of command"),
        "Charge of the Light Brigade Crimean War",
    ),
    _e(
        "potato_famine_1847",
        "Ireland — Famine Relief",
        "nineteenth",
        "1847",
        "Ireland",
        "Humanitarian crisis",
        "Potato blight has returned. Workhouses overflow. Peel and Russell governments debate corn imports, public works, and landlord responsibility. Some exports still leave Ireland.",
        "As a British relief official, what combination of food aid, employment, and trade policy do you advocate?",
        "Relief was inadequate, doctrinaire, and late; exports continued amid starvation.",
        "Roughly one million died; mass emigration reshaped Ireland and America.",
        ("food imports", "workhouse conditions", "landlord relief duty", "export restrictions", "local administration"),
        "Irish potato famine nineteenth century",
    ),
    _e(
        "emancipation_1862",
        "Washington — Emancipation Timing",
        "nineteenth",
        "1862",
        "USA",
        "Civil war & rights",
        "Union morale wavers after Antietam. Lincoln considers emancipation proclamation. Cabinet warns of border states, courts, and midterm elections. Foreign recognition of Confederacy is a risk.",
        "When and how do you recommend Lincoln issue emancipation — and what exceptions?",
        "Lincoln waited for Antietam victory; preliminary proclamation September 1862.",
        "Emancipation reframed war aims; implementation followed military advance.",
        ("border states", "foreign opinion", "military timing", "legal durability", "political backlash"),
        "Lincoln Emancipation Proclamation Civil War",
    ),
    _e(
        "gettysburg_1863",
        "Gettysburg — Day Three Charge",
        "nineteenth",
        "1863",
        "Pennsylvania",
        "Civil war",
        "After two days' fighting, Lee orders Pickett's division plus others to assault the Union center on Cemetery Ridge. Longstreet opposes. Artillery preparation is uncertain.",
        "As Confederate adviser on July 3, do you support the assault — and what alternative?",
        "Lee ordered Pickett's Charge; Union repulsed it with heavy Confederate losses.",
        "Gettysburg turned the war's momentum; Lee retreated south.",
        ("artillery effectiveness", "Union center strength", "flank alternatives", "casualty cost", "withdrawal option"),
        "Pickett's Charge Gettysburg Civil War",
    ),
    _e(
        "rorke_drift_1879",
        "Rorke's Drift — Defense With Few",
        "nineteenth",
        "1879",
        "Zululand",
        "Colonial warfare",
        "After Isandlwana, four thousand Zulu warriors attack Rorke's Drift. About 150 troops hold with mealie-bag barricades. Ammunition is limited; relief is distant.",
        "How do you organize defense, ammunition discipline, and fallback positions?",
        "Chard and Bromhead fortified compound and inner redoubt; held until dawn.",
        "Defenders held; eleven Victoria Crosses awarded.",
        ("perimeter and redoubt", "ammo distribution", "fire discipline", "medical care", "surrender vs hold"),
        "Rorke's Drift Zulu War defense",
    ),
    _e(
        "isandlwana_1879",
        "Isandlwana — Camp Discipline",
        "nineteenth",
        "1879",
        "Zululand",
        "Colonial warfare",
        "British column camps below Isandlwana hill without entrenching. Scouts report Zulu impis nearby. Ammunition boxes are screwed shut; distribution is slow. Chelmsford has split the force.",
        "With Zulu forces massing, what camp security and ammunition orders do you issue immediately?",
        "Dispersed units, slow ammo resupply, and underestimated Zulu attack led to disaster.",
        "British force annihilated; Rorke's Drift followed same day.",
        ("entrenchments", "ammo boxes open", "scouting", "concentrated force", "ridge defense"),
        "Battle of Isandlwana Zulu warriors",
    ),
    _e(
        "berlin_conference_1884",
        "Berlin Conference — African Borders",
        "nineteenth",
        "1884–1885",
        "Europe / Africa",
        "Colonial diplomacy",
        "European powers meet to set rules for African claims without African representation. Trade, missions, and effective occupation are debated. Rivalry could spark European war.",
        "As a British delegate, what principles do you push for claiming and governing African territories?",
        "Conference recognized Leopold's Congo and set 'effective occupation' standard.",
        "Scramble for Africa accelerated; arbitrary borders lasted into independence era.",
        ("effective occupation", "free trade Congo", "coastal vs interior claims", "African sovereignty ignored", "European war risk"),
        "Berlin Conference Africa colonial map",
    ),
    _e(
        "boxer_1900",
        "Beijing — Boxer Siege",
        "twentieth",
        "1900",
        "China",
        "Imperial crisis",
        "Boxers besiege the Legation Quarter in Beijing. Empress Dowager backs them. Foreign powers assemble relief expedition. Chinese moderates urge compromise.",
        "As a Qing adviser, do you suppress Boxers, join them, or negotiate — knowing foreign fleets approach?",
        "Court vacillated; siege ended when Eight-Nation Alliance relieved legations.",
        "Boxer Protocol imposed heavy indemnities; Qing authority weakened further.",
        ("foreign retaliation", "legation safety", "domestic legitimacy", "regional governors", "indemnity risk"),
        "Boxer Rebellion Beijing legation siege",
    ),
    _e(
        "titanic_1912",
        "Titanic — Lifeboat Loading",
        "twentieth",
        "1912",
        "North Atlantic",
        "Maritime disaster",
        "Titanic is sinking; lifeboats for roughly half aboard. Many passengers do not understand severity. Crew training on davits is uneven. Women-and-children policy is announced.",
        "As officer at a lifeboat station, how do you load boats and communicate urgency?",
        "Many boats left partially filled; lack of drill and complacency cost lives.",
        "Over 1,500 died; safety regulations and wireless practices changed globally.",
        ("fill boats fully", "clear orders", "wireless distress", "class access", "early evacuation"),
        "Titanic lifeboats sinking ship 1912",
    ),
    _e(
        "christmas_truce_1914",
        "Western Front — Christmas 1914",
        "twentieth",
        "1914",
        "France / Belgium",
        "World War I",
        "Soldiers in trenches spontaneously fraternize on Christmas. Officers fear truce lines weaken fighting spirit. Artillery schedules resume soon. High command forbids repeats.",
        "As a front-line commander witnessing fraternization, what orders do you issue?",
        "Local truces occurred; high command cracked down afterward.",
        "Truce was brief; war of attrition continued for years.",
        ("discipline vs humanity", "trench security", "high command orders", "propaganda risk", "renewed attacks"),
        "Christmas truce 1914 trenches soldiers",
    ),
    _e(
        "treaty_versailles_1919",
        "Versailles — German Terms",
        "twentieth",
        "1919",
        "Europe",
        "Diplomacy",
        "Allied leaders debate peace. France wants security and reparations; Britain balance; Wilson wants League. Germans must sign or face renewed war.",
        "As British delegate, what balance between reparations, territory, and stability do you argue for?",
        "Treaty imposed guilt clause, reparations, territorial losses, military limits.",
        "German resentment fed Weimar instability and revisionism.",
        ("sustainable reparations", "French security", "German humiliation", "League membership", "economic recovery"),
        "Treaty of Versailles 1919 signing",
    ),
    _e(
        "russian_rev_1917",
        "Petrograd — October Decision",
        "twentieth",
        "1917",
        "Russia",
        "Revolution",
        "Provisional Government weakens; Bolsheviks control soviets in key cities. Kerensky moves against them. Lenin urges insurrection; some Bolsheviks urge waiting for Congress of Soviets.",
        "As a Bolshevik leader, do you launch insurrection before the Congress — or wait?",
        "Bolsheviks seized key points overnight before Congress opened.",
        "Provisional Government fell; civil war followed.",
        ("timing of Congress", "military loyalty", "popular support", "German peace issue", "allied reaction"),
        "Russian Revolution October 1917 Petrograd",
    ),
    _e(
        "munich_1938",
        "Munich — Czechoslovakia",
        "twentieth",
        "1938",
        "Czechoslovakia",
        "Appeasement",
        "Hitler demands Sudetenland. Czechoslovakia has alliances and strong border defenses. Britain and France may abandon Prague. Stalin is not invited; Czechs are not at table.",
        "As a British adviser to Chamberlain, do you accept Hitler's terms, guarantee borders, or threaten war?",
        "Chamberlain flew to Munich; Sudetenland ceded; 'peace for our time.'",
        "Germany occupied Bohemia-Moravia months later; appeasement discredited.",
        ("Czech defenses", "Soviet pact option", "public opinion", "Hitler's credibility", "alliance honor"),
        "Munich Agreement 1938 Chamberlain Hitler",
    ),
    _e(
        "pearl_harbor_intel_1941",
        "Pearl Harbor — Warning Signs",
        "twentieth",
        "1941",
        "Hawaii",
        "Intelligence failure",
        "Purple code messages suggest negotiations ending. Radar is new and understaffed. Fleet concentrated at Pearl. Some expect attack in Southeast Asia only.",
        "What alerts and defensive measures do you recommend for the Pacific Fleet in late November?",
        "Warnings were vague; aircraft parked tightly; attack came December 7.",
        "Battleship force devastated; U.S. entered WWII.",
        ("ambiguous indicators", "dispersal vs readiness", "air patrol", "Army-Navy coordination", "operational warning"),
        "Pearl Harbor 1941 battleships attack",
    ),
    _e(
        "leningrad_blockade_1941",
        "Siege of Leningrad — Evacuate or Endure",
        "twentieth",
        "1941–1942",
        "Soviet Union",
        "Civilian crisis",
        "Leningrad encircled. Road of Life is ice-dependent. Rations collapse. Stalin demands hold. Hundreds of thousands trapped.",
        "What policy do you argue for civilians, food, and production with uncertain relief?",
        "Evacuation over Ladoga when ice allowed; extreme rationing; mass death.",
        "Roughly one million civilians died; city did not surrender.",
        ("selective evacuation", "ration triage", "war production", "winter ice route", "surrender cost"),
        "Siege of Leningrad winter civilians",
    ),
    _e(
        "battle_britain_1940",
        "Battle of Britain — Fighter Reserve",
        "twentieth",
        "1940",
        "Britain",
        "World War II",
        "Luftwaffe shifts between airfields, radar sites, and London. Fighter Command losses mount. Dowding faces pressure to send more planes to France. Invasion barges gather.",
        "How do you allocate fighters between defending airfields, cities, and keeping a reserve?",
        "Dowding conserved reserves; radar and sector control proved decisive.",
        "Germany failed to gain air superiority; invasion threat faded.",
        ("reserve squadrons", "radar protection", "pilot exhaustion", "civilian morale", "invasion timing"),
        "Battle of Britain Spitfire fighters 1940",
    ),
    _e(
        "stalingrad_1943",
        "Stalingrad — Paulus Encircled",
        "twentieth",
        "1943",
        "Soviet Union",
        "World War II",
        "Sixth Army encircled in Stalingrad. Hitler orders hold; airlift insufficient. Manstein proposes breakout. Frost and Soviet rings tighten.",
        "As German staff officer, do you urge breakout, hold for relief, or negotiate — with what costs?",
        "Hitler refused breakout; Paulus surrendered January 1943.",
        "Turning point on Eastern Front; German offensive capacity shattered.",
        ("airlift limits", "breakout window", "Hitler order", "civilian city", "Soviet reserves"),
        "Battle of Stalingrad winter ruins",
    ),
    _e(
        "dday_weather_1944",
        "D-Day — Weather Call",
        "twentieth",
        "1944",
        "Western Europe",
        "Military planning",
        "Meteorologists report a brief June 6 break then worsening weather. Tides constrain window. Postponement risks discovery.",
        "Proceed, postpone, or wait — how do you justify the call?",
        "Eisenhower launched June 6 despite rough seas.",
        "Overlord succeeded; later delay would have hit another storm.",
        ("meteorological uncertainty", "tide constraints", "secrecy vs delay", "casualty trade-offs", "command consensus"),
        "D-Day Normandy invasion ships 1944",
    ),
    _e(
        "manhattan_project_1945",
        "Manhattan Project — Use of the Bomb",
        "twentieth",
        "1945",
        "USA / Pacific",
        "Ethics & war",
        "Trinity succeeded. Japan rejects Potsdam terms. Invasion casualties projected high. Scientists urge demonstration.",
        "What do you recommend on atomic deployment and alternatives?",
        "Truman authorized use on cities; some advisers favored demonstration.",
        "Hiroshima and Nagasaki bombed; Japan surrendered August 15.",
        ("invasion estimates", "surrender signals", "demonstration option", "Soviet entry", "arms race foresight"),
        "atomic bomb mushroom cloud 1945",
    ),
    _e(
        "salt_march_1930",
        "Gandhi — Salt March Strategy",
        "twentieth",
        "1930",
        "British India",
        "Resistance",
        "Britain taxes salt. Gandhi plans 240-mile march. Authorities debate early arrest versus letting protest grow.",
        "How do you structure the campaign after the march begins?",
        "Gandhi made salt and was arrested; movement spread nationwide.",
        "Over 60,000 arrested; turning point toward independence.",
        ("symbolic target", "non-violence", "media visibility", "follow-on acts", "British response"),
        "Gandhi Salt March India 1930",
    ),
    _e(
        "cuban_missile_1962",
        "Cuban Missile Crisis — Blockade Decision",
        "twentieth",
        "1962",
        "Caribbean",
        "Cold War",
        "Soviet missiles confirmed in Cuba. Joint Chiefs urge invasion. Soviet ships approach quarantine line.",
        "What course do you recommend for the next forty-eight hours?",
        "Kennedy imposed quarantine; secret diplomacy with Khrushchev ran parallel.",
        "Missiles removed in exchange for secret no-invasion pledge and Turkey missile withdrawal.",
        ("escalation risk", "time for diplomacy", "allied consultation", "public vs private channels", "nuclear brinkmanship"),
        "Cuban Missile Crisis naval blockade 1962",
    ),
    _e(
        "berlin_wall_1961",
        "Berlin — Wall Goes Up",
        "twentieth",
        "1961",
        "Germany",
        "Cold War",
        "East Germany seals sectors overnight. Tanks face at Checkpoint Charlie. Kennedy is cautious after Vienna.",
        "How should the U.S. respond in the first week — militarily, diplomatically, for Berliners?",
        "Kennedy did not use force to tear down barriers; symbolic reassurance followed.",
        "Wall stood until 1989; crisis froze into partition without nuclear war.",
        ("avoid nuclear escalation", "symbolic reassurance", "allied unity", "fait accompli", "long-game containment"),
        "Berlin Wall tanks Checkpoint Charlie 1961",
    ),
    _e(
        "suez_1956",
        "Suez — Canal Seizure",
        "twentieth",
        "1956",
        "Egypt",
        "Colonial war",
        "Nasser nationalizes Suez Canal. Britain, France, and Israel plan secret military action. U.S. opposes; Soviet threats loom. UN pressure builds.",
        "As British adviser, do you support joint intervention or diplomatic track?",
        "Britain, France, and Israel attacked; U.S. pressure and Soviet threats forced ceasefire.",
        "Humiliation for Britain and France; Nasser survived; Eisenhower Doctrine followed.",
        ("U.S. opposition", "Soviet threats", "UN role", "Israel coordination", "canal operation"),
        "Suez Crisis 1956 canal ships",
    ),
    _e(
        "apollo_13_1970",
        "Apollo 13 — CO₂ Scrubber Crisis",
        "twentieth",
        "1970",
        "Space",
        "Science & crisis",
        "Explosion crippled Apollo 13. LM supports three for four days. CO₂ rising; square cartridges do not fit round CM openings.",
        "What immediate priorities and improvised solutions do you order?",
        "Houston built 'mailbox' adapter; free-return trajectory succeeded.",
        "Crew splashed down safely April 17.",
        ("CO₂ adapter", "power budgeting", "trajectory", "crew procedures", "ground collaboration"),
        "Apollo 13 spacecraft mission control crisis",
    ),
    _e(
        "nixon_china_1972",
        "Opening to China — Recognition Gamble",
        "twentieth",
        "1972",
        "Asia",
        "Diplomacy",
        "U.S. does not recognize PRC; Taiwan holds UN seat. Sino-Soviet split offers opening. Conservatives and allies fear abandonment.",
        "How do you sequence rapprochement while managing Taiwan and Congress?",
        "Ping-pong diplomacy preceded Nixon visit; Shanghai Communiqué followed.",
        "Relations normalized gradually; Taiwan dispute continued.",
        ("Soviet triangle", "Taiwan assurances", "gradual normalization", "secret channel", "domestic politics"),
        "Nixon visits China 1972 diplomacy",
    ),
    _e(
        "tet_offensive_1968",
        "Tet Offensive — Media Narrative",
        "twentieth",
        "1968",
        "Vietnam",
        "War & public opinion",
        "VC and NVA attack cities during truce. Saigon fighting shocks TV audiences. Militarily attacks fail but psychologically shake U.S. confidence.",
        "As U.S. spokesman after Tet, how do you describe progress without losing credibility?",
        "Westmoreland requested more troops; Cronkite questioned stalemate; Johnson declined reelection.",
        "Public support eroded despite tactical U.S. victories.",
        ("credibility gap", "enemy resilience", "tactical vs strategic", "domestic opinion", "negotiation path"),
        "Tet Offensive Saigon fighting 1968",
    ),
    _e(
        "saigon_1975",
        "Saigon — Final Evacuation",
        "twentieth",
        "1975",
        "Vietnam",
        "War & evacuation",
        "NVA closes on Saigon. Fixed-wing evacuation ends after crash. Helicopter lifts from embassy roof limited. South Vietnamese allies plead for seats.",
        "With hours left, how do you prioritize evacuees and manage crowd control?",
        "Operation Frequent Wind lifted thousands; many allies left behind.",
        "Saigon fell April 30; Vietnam reunified under communist rule.",
        ("helicopter capacity", "ally commitments", "crowd security", "fixed-wing loss", "symbolic deadline"),
        "Saigon helicopter evacuation embassy 1975",
    ),
    _e(
        "iran_hostage_1979",
        "Tehran — Embassy Hostages",
        "twentieth",
        "1979",
        "Iran",
        "Crisis diplomacy",
        "Students seize U.S. embassy after Shah admitted to U.S. for medical care. Carter faces rescue, sanctions, or negotiation. Hostages are scattered.",
        "What combined diplomatic, economic, and military steps do you recommend in the first month?",
        "Carter froze assets and negotiated; rescue attempt failed in desert.",
        "Hostages held 444 days; released after Reagan inaugurated.",
        ("rescue feasibility", "sanctions", "Shah issue", "allied support", "hostage safety"),
        "Iran hostage crisis embassy Tehran 1979",
    ),
    _e(
        "chernobyl_1986",
        "Chernobyl — Reactor 4 Explosion",
        "twentieth",
        "1986",
        "Soviet Ukraine",
        "Disaster response",
        "Reactor 4 exploded during a test. Graphite burns; Pripyat sleeps. Managers disagree on severity. Firefighters lack radiation knowledge.",
        "In the first six hours, what evacuation, firefighting, and reporting do you order?",
        "Delayed Pripyat evacuation; firefighters unprotected; helicopters dropped sand and boron.",
        "Exclusion zone created; long-term health and political consequences.",
        ("evacuation radius", "firefighter protection", "upward reporting", "contamination spread", "public warning"),
        "Chernobyl nuclear disaster fire reactor",
    ),
    _e(
        "berlin_wall_fall_1989",
        "Berlin — Wall Opens",
        "twentieth",
        "1989",
        "Germany",
        "Revolution",
        "East German spokesman botches travel rules; crowds mass at checkpoints. Stasi and army tense. West Berlin celebrates.",
        "As East German official facing crowds, do you open checkpoints, use force, or negotiate — tonight?",
        "Guards yielded; crowds crossed; wall effectively open November 9.",
        "Germany reunified within a year; Cold War neared end.",
        ("crowd violence risk", "Soviet reaction", "regime legitimacy", "controlled vs free travel", "officer orders"),
        "Berlin Wall falls 1989 crowds celebration",
    ),
    _e(
        "nine_eleven_2001",
        "U.S. Airspace — Ground Stop",
        "twenty_first",
        "2001",
        "USA",
        "Crisis response",
        "Multiple hijackings confirmed; towers struck. Thousands of aircraft airborne. NORAD and FAA struggle coordination. Unclear if more attacks coming.",
        "What immediate airspace and communication orders do you issue nationwide?",
        "FAA ordered national ground stop; aircraft diverted; last commercial flights landed hours later.",
        "Nearly 3,000 dead; security and foreign policy transformed.",
        ("ground stop scope", "military escorts", "airport screening", "communication clarity", "continuity of government"),
        "September 11 air traffic control crisis",
    ),
    _e(
        "fukushima_2011",
        "Fukushima — Tsunami Aftermath",
        "twenty_first",
        "2011",
        "Japan",
        "Nuclear disaster",
        "Earthquake and tsunami knocked out power. Reactors need cooling; hydrogen builds. Evacuation zones debated. Information is incomplete.",
        "In the first 24 hours, what evacuation radius and cooling priorities do you set?",
        "Delayed venting and seawater injection; explosions followed; zone expanded.",
        "Long-term evacuation; nuclear policy debated globally.",
        ("cooling priority", "evacuation radius", "information transparency", "seawater injection", "worker safety"),
        "Fukushima nuclear plant tsunami disaster",
    ),
    _e(
        "arab_spring_2011",
        "Tunisia — Ben Ali Flees",
        "twenty_first",
        "2011",
        "Tunisia",
        "Revolution",
        "Mass protests after vendor self-immolation. Army chief must choose loyalty. Ben Ali offers reforms too late. Social media spreads unrest.",
        "As senior general, do you support the president, defend protesters, or broker transition?",
        "Army refused to fire on crowds; Ben Ali fled January 14.",
        "Inspired regional uprisings; Tunisia later pursued fragile democracy.",
        ("army neutrality", "violence escalation", "transition government", "economic grievances", "regional contagion"),
        "Arab Spring Tunisia protest revolution",
    ),
    _e(
        "covid_lockdown_2020",
        "Wuhan — First Lockdown Decision",
        "twenty_first",
        "2020",
        "China",
        "Public health",
        "Novel pneumonia clusters grow. Lunar New Year travel imminent. Economic cost of city closure is enormous. International notification incomplete.",
        "As provincial leader, do you lock down a megacity — and what do you communicate publicly?",
        "Wuhan locked down January 23; restrictions spread nationally.",
        "Pandemic became global; debate over speed, transparency, and economic trade-offs.",
        ("travel timing", "economic cost", "transparent reporting", "hospital capacity", "enforcement"),
        "COVID lockdown empty city masks 2020",
    ),
]

assert len(ALL_ENCOUNTERS) >= 50, len(ALL_ENCOUNTERS)
